apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: nginxjs
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginxjs
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: nginxjs
        color: blue
    spec:
      containers:
      - image: docker.io/takupaca/citest:14069c32311f0a9ef4ffaa4abc83408ffbcb8bbe
        name: blue
        ports:
          - containerPort: 80
